name: ecr-login
on:
  # Every 6 hours, the password validity is 12 hours
  schedule:
    - cron:  '0 */6 * * *'
  push:
    branches: [ himanshu-ecr-demo ]
jobs:
  login:
    runs-on: ubuntu-latest
    container:
      image: python:3.8-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@v1.1
      - name: retrieve ecr password and store as secret
        run: |
          aws --version
          pip3 install -r .github/requirements.txt
          python3 .github/ecr_password_updater.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
          GH_API_ACCESS_TOKEN: ${{ secrets.GH_API_ACCESS_TOKEN }}
          
  test:
    needs: login
    runs-on: ubuntu-latest
    container:
      image: 133615223499.dkr.ecr.ap-south-1.amazonaws.com/ecr-test-repo:latest
      credentials:
        username: AWS
        password: ${{ secrets.REGISTRY_PASSWORD }}
    steps:
      - run: echo "Inside a container pulled from ECR \o/"
